## NumPy Array Iterating



In [1]:
import numpy as np

In [2]:

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [3]:
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6]], 
                 [[7, 8, 9], 
                  [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [4]:
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6]], 
                 [[7, 8, 9], 
                  [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()


In [5]:
arr = np.array([[[1, 2], 
                 [3, 4]], 
                 [[5, 6], 
                  [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [6]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])
print(arr[0:3, 0:4 :2])
for x in np.nditer(arr[:, ::2]):
  print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
1
3
5
7
9
11


##  ndenumerate() 


In [7]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
