In [4]:
import numpy as np

In [5]:
arr_1d = np.array( [1, 2, 3 ,4 ])
print("1d array" , arr_1d)

arr_2d = np.array( [[1, 2, 3 ,4 ], [1,2,3,4]])
print("2d array" , arr_2d)

1d array [1 2 3 4]
2d array [[1 2 3 4]
 [1 2 3 4]]


In [6]:
py_list = [1, 2 ,3]
print(py_list*2)

np_list = np.array([[1, 2 ,3],[4, 5, 6]])
print(np_list*2)
np_list = np_list.T

print(np_list)

[1, 2, 3, 1, 2, 3]
[[ 2  4  6]
 [ 8 10 12]]
[[1 4]
 [2 5]
 [3 6]]


##  sorting


In [7]:

unsorted = np.array([3,4,5,2,1,0,7,3])
print(f"sorted Array {np.sort(unsorted)}")

arrr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(f"sorted Array by coloum {np.sort(arrr_2d_unsorted, axis=0)}")
print(f"sorted Array by roe {np.sort(arrr_2d_unsorted, axis=1)}")


sorted Array [0 1 2 3 3 4 5 7]
sorted Array by coloum [[1 1]
 [2 2]
 [3 3]]
sorted Array by roe [[1 3]
 [1 2]
 [2 3]]


In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


##  filter

In [9]:
numbers = np.arange(0,11)
print(numbers)
even_number = numbers[numbers % 2 == 0]
print(even_number)
odd_number = numbers[numbers % 2 == 1]
print(odd_number)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[1 3 5 7 9]


## Filter with mask

In [10]:
mask = numbers > 5
print(f"numbers grater than 5 {numbers[mask]}")

numbers grater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [11]:
indices = [0,2,4,6,8]
print(numbers[indices])
where_result = np.where(numbers > 5)
print(f"NP where() {numbers[where_result]}")

[0 2 4 6 8]
NP where() [ 6  7  8  9 10]


In [12]:
# for number in numbers:
#     if (number > 5):
#         print("true")
#     else:
#         print("false")

condition_array = np.where(numbers > 5 , "true", "false")
print(f"array = {condition_array}")


array = ['false' 'false' 'false' 'false' 'false' 'false' 'true' 'true' 'true'
 'true' 'true']


## adding and removing data

In [13]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

combine = np.concatenate((arr1, arr2))
print(combine)

[ 1  2  3  4  5  6  7  8  9 10]


## array compatbility

In [14]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
arr3 = np.arange(11,17)
combine = np.concatenate((arr1, arr2, arr3))
print(combine)
print("Compatibility Shaper ", arr1.shape == arr2.shape)
print("Compatibility Shaper ", arr1.shape == arr3.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Compatibility Shaper  True
Compatibility Shaper  False


In [15]:
orignal = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
new_coloum = np.array([[7],[8],[9]])

row = np.vstack((orignal, new_row))
print(f"new row =\n{row}")
coloum = np.hstack((row, new_coloum))
print(f"new coloum =\n{coloum}")


new row =
[[1 2]
 [3 4]
 [5 6]]
new coloum =
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [16]:
arr = np.array([10,20,30,40,50,60])
deleted = np.delete(arr, 2) # index not number
print(deleted)

[10 20 40 50 60]


## spliting the data 

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
